name: cloudflare

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm install

      - name: Deploy
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiKey: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secrets: |
            API_KEY
        env:
          API_KEY: ${{ secrets.API_KEY }}
